### ISSUE TITLE
Double Slabs integration/Vertical Slabs in Redstone category

### ISSUE THREAD

**Issue by Dabreu131** [RahalaBytes/LottaTerracotta#4] opened 2020-07-05 00:06 UTC
The Double Slabs mod recently added vertical slab compatibility, specifically for Quark, though it's supposed to work with anny mod. I think it has something to do with vertical slabs being considered part of the Redstone category. Is there some reason why they're not considered Building Blocks or is it just a bug?

I have disabled fences, ladders, pressure plates and levers in the config file.

**Comment by Angela** [comment] 2020-07-05 02:09
@Dabreu131 Thanks for your report! The vertical slabs being in the Redstone category is a bug, they are definitely meant to be in the Building Blocks category. 

I doubt this is the cause of Double Slabs integration not working, but I'll take a look and see if I can get that fixed as well for the next release.

**Comment by Angela** [comment] 2020-07-16 19:32
Fixed in the latest version of Double Slabs

**Closed as completed by Angela** 2020-07-16 19:32 UTC
